export type ProductCategory =
  | "Bouquets"
  | "Keychains"
  | "Magnets & pots"
  | "Clips & brooches"
  | "Torans & garlands";

export type Product = {
  id: string;
  title: string;
  category: ProductCategory;
  image: string;
  blurb: string;
  priceFrom: number;
};

export const priceBands: { category: ProductCategory; from: number; note: string }[] =
  [
    { category: "Keychains", from: 49, note: "Single flower charm" },
    { category: "Magnets & pots", from: 79, note: "Mini pots & fridge stems" },
    { category: "Clips & brooches", from: 99, note: "Wearable blooms" },
    { category: "Bouquets", from: 299, note: "Gift-wrapped forever florals" },
    { category: "Torans & garlands", from: 199, note: "Door hangings & malas" },
  ];

export const products: Product[] = [
  {
    id: "keychain-rack",
    title: "Flower keychains",
    category: "Keychains",
    image: "/products/15-b378e372-4770-40e4-8444-c5d16d6b7704.png",
    blurb: "Soft chenille blooms on gold rings — pocket-sized joy.",
    priceFrom: 49,
  },
  {
    id: "keychain-display",
    title: "Market stall blooms",
    category: "Keychains",
    image: "/products/11-6b917510-7e98-49f1-bc1b-993bad756e23.png",
    blurb: "A rainbow of handmade flower keychains.",
    priceFrom: 49,
  },
  {
    id: "sunflower-bouquet",
    title: "Sunflower bouquet",
    category: "Bouquets",
    image: "/products/18-f7d9f4a8-c8fa-4835-843b-3841711ad9f5.png",
    blurb: "Forever sunflowers wrapped ready to gift.",
    priceFrom: 399,
  },
  {
    id: "orange-lilies",
    title: "Orange lily wrap",
    category: "Bouquets",
    image: "/products/23-ceb02a4b-6214-44a1-874e-33e77a507c27.png",
    blurb: "Warm orange lilies with pearl centers.",
    priceFrom: 349,
  },
  {
    id: "purple-bouquet",
    title: "Lavender stem set",
    category: "Bouquets",
    image: "/products/22-34863507-c019-4703-9be7-44b3919e52ac.png",
    blurb: "Soft purple stems tied with a green ribbon.",
    priceFrom: 299,
  },
  {
    id: "pink-bouquet",
    title: "Pink lily gift",
    category: "Bouquets",
    image: "/products/16-5553eaee-0675-49f1-a938-35f2897f1d5e.png",
    blurb: "Blush pink with daisy accents.",
    priceFrom: 349,
  },
  {
    id: "red-white-bouquet",
    title: "Red & white lilies",
    category: "Bouquets",
    image: "/products/19-a318ecdb-b3fe-4872-b136-bb31f541f45c.png",
    blurb: "Bold red and white, gold-trimmed wrap.",
    priceFrom: 399,
  },
  {
    id: "violet-mesh",
    title: "Violet mesh bouquet",
    category: "Bouquets",
    image: "/products/20-441802a6-0241-4ad6-8c5d-7d5eb979f92c.png",
    blurb: "Purple blooms in pearl-edge tulle.",
    priceFrom: 379,
  },
  {
    id: "sunflower-gift",
    title: "Sunflower gift wrap",
    category: "Bouquets",
    image: "/products/17-ba27fb26-daa0-4237-918c-224d668542de.png",
    blurb: "Yellow ribbon, black mesh, ready for celebration.",
    priceFrom: 399,
  },
  {
    id: "yellow-red-set",
    title: "Sunflower & cake set",
    category: "Bouquets",
    image: "/products/30-53e2f0e2-8947-40cb-b06b-60072705d835.png",
    blurb: "Bouquets and mini cake decor for gifting.",
    priceFrom: 499,
  },
  {
    id: "heart-pot",
    title: "Heart flower pot",
    category: "Magnets & pots",
    image: "/products/21-cf5b131e-68ab-40c7-abeb-5c73adea916a.png",
    blurb: "Tiny potted hearts — desk or fridge charm.",
    priceFrom: 129,
  },
  {
    id: "red-pot",
    title: "Red bloom pot",
    category: "Magnets & pots",
    image: "/products/25-64c4072e-1530-4653-b6c2-bebeb20aa6db.png",
    blurb: "Palm-sized fuzzy florals in a craft pot.",
    priceFrom: 149,
  },
  {
    id: "sunflower-pots",
    title: "Mini sunflower pots",
    category: "Magnets & pots",
    image: "/products/24-5ee1725c-b4fe-4674-b45f-ebb46dac0267.png",
    blurb: "A whole sunny set for shelves and gifts.",
    priceFrom: 99,
  },
  {
    id: "hair-clips",
    title: "Crochet flower clips",
    category: "Clips & brooches",
    image: "/products/27-36f327cb-dd55-4f59-a12e-184df44e4a11.png",
    blurb: "Premium soft yarn blooms on alligator clips.",
    priceFrom: 99,
  },
  {
    id: "sunflower-brooch",
    title: "Sunflower brooches",
    category: "Clips & brooches",
    image: "/products/28-d03dda33-34c4-4403-80c9-62a6b2322fed.png",
    blurb: "Wearable sunshine pins.",
    priceFrom: 79,
  },
  {
    id: "magnet-stems",
    title: "Stem magnets",
    category: "Magnets & pots",
    image: "/products/29-bbeadd45-fa3b-4294-8a77-ad951434f30f.png",
    blurb: "Vertical flower magnets for fridge doors.",
    priceFrom: 79,
  },

  {
    id: "bouquet-pink-lily-daisy",
    title: "Pink lily & daisy stem",
    category: "Bouquets",
    image: "/products/bouquet-pink-lily-daisy.jpg",
    blurb: "A single lily with white daisies in a soft cone wrap.",
    priceFrom: 299,
  },
  {
    id: "bouquet-pink-lily-cone",
    title: "Pink lily bouquet",
    category: "Bouquets",
    image: "/products/bouquet-pink-lily-cone.jpg",
    blurb: "Lily and daisies in white paper, finished with an organza bow.",
    priceFrom: 299,
  },
  {
    id: "bouquet-lilac-yellow",
    title: "Lilac & sunshine bouquet",
    category: "Bouquets",
    image: "/products/bouquet-lilac-yellow.jpg",
    blurb: "Lilac daisies with a yellow lily, wrapped in blush pink.",
    priceFrom: 349,
  },
  {
    id: "bouquet-lilac-gold-bow",
    title: "Lilac bouquet, gold bow",
    category: "Bouquets",
    image: "/products/bouquet-lilac-gold-bow.jpg",
    blurb: "The lilac set finished with a wide gold ribbon.",
    priceFrom: 379,
  },
  {
    id: "bouquet-blue-gerbera",
    title: "Blue gerbera bouquet",
    category: "Bouquets",
    image: "/products/bouquet-blue-gerbera.jpg",
    blurb: "Cool blues and white with a gold organza bow.",
    priceFrom: 349,
  },
  {
    id: "bouquet-pink-gerbera",
    title: "Pink gerbera bouquet",
    category: "Bouquets",
    image: "/products/bouquet-pink-gerbera.jpg",
    blurb: "Blush gerberas in white paper with a lace ribbon.",
    priceFrom: 349,
  },
  {
    id: "bouquet-purple-daisy",
    title: "Purple daisy stem",
    category: "Bouquets",
    image: "/products/bouquet-purple-daisy.jpg",
    blurb: "A purple daisy and lily pair in a crisp white wrap.",
    priceFrom: 299,
  },
  {
    id: "bouquet-single-sunflower",
    title: "Single sunflower",
    category: "Bouquets",
    image: "/products/bouquet-single-sunflower.jpg",
    blurb: "One big sunflower in kraft paper with a red bow — small, complete gift.",
    priceFrom: 249,
  },
  {
    id: "bouquet-bunny-hearts",
    title: "Bunny & hearts bouquet",
    category: "Bouquets",
    image: "/products/bouquet-bunny-hearts.jpg",
    blurb: "Pink lilies, hearts and little bunnies — made for anniversaries.",
    priceFrom: 449,
  },
  {
    id: "keychain-sunflower-yellow",
    title: "Sunflower keychain",
    category: "Keychains",
    image: "/products/keychain-sunflower-yellow.jpg",
    blurb: "The bestseller — brown centre, bright yellow petals.",
    priceFrom: 49,
  },
  {
    id: "keychain-blue-blossom",
    title: "Blue blossom keychain",
    category: "Keychains",
    image: "/products/keychain-blue-blossom.jpg",
    blurb: "A soft five-petal bloom in powder blue.",
    priceFrom: 49,
  },
  {
    id: "keychain-magenta-daisy",
    title: "Magenta daisy keychain",
    category: "Keychains",
    image: "/products/keychain-magenta-daisy.jpg",
    blurb: "Deep pink petals with a golden middle.",
    priceFrom: 49,
  },
  {
    id: "keychain-pink-lily",
    title: "Pink lily keychain",
    category: "Keychains",
    image: "/products/keychain-pink-lily.jpg",
    blurb: "A full lily head with a pearl centre.",
    priceFrom: 59,
  },
  {
    id: "keychain-nazar-blue",
    title: "Nazar bag charm",
    category: "Keychains",
    image: "/products/keychain-nazar-blue.jpg",
    blurb: "A blue evil-eye bloom trailing pearls and little blossoms.",
    priceFrom: 129,
  },
  {
    id: "magnet-sunflower-bunch",
    title: "Sunflower magnet bunch",
    category: "Magnets & pots",
    image: "/products/magnet-sunflower-bunch.jpg",
    blurb: "Three sunflowers tied with a pearl — one magnet, big impact.",
    priceFrom: 129,
  },
  {
    id: "magnet-yellow-lily",
    title: "Yellow lily magnet",
    category: "Magnets & pots",
    image: "/products/magnet-yellow-lily.jpg",
    blurb: "A tall lily with a ribbon curl, straight onto the fridge door.",
    priceFrom: 99,
  },
  {
    id: "magnet-red-hibiscus",
    title: "Red hibiscus magnet",
    category: "Magnets & pots",
    image: "/products/magnet-red-hibiscus.jpg",
    blurb: "Bold red petals with a long green leaf spray.",
    priceFrom: 99,
  },
  {
    id: "magnet-hibiscus-stem",
    title: "Hibiscus stem magnet",
    category: "Magnets & pots",
    image: "/products/magnet-hibiscus-stem.jpg",
    blurb: "Red petals, yellow centre, curling green stem.",
    priceFrom: 99,
  },
  {
    id: "magnet-collection",
    title: "Fridge magnet collection",
    category: "Magnets & pots",
    image: "/products/magnet-collection.jpg",
    blurb: "The full spread of mini flower bunches — pick your colours by the dozen.",
    priceFrom: 79,
  },
  {
    id: "magnet-fries",
    title: "Fries magnet",
    category: "Magnets & pots",
    image: "/products/magnet-fries.jpg",
    blurb: "A cheeky custom order — anything you sketch, we can shape in chenille.",
    priceFrom: 149,
  },
  {
    id: "clips-sunflower-pair",
    title: "Sunflower snap clips",
    category: "Clips & brooches",
    image: "/products/clips-sunflower-pair.jpg",
    blurb: "A pair of sunny clips on sturdy snap bases.",
    priceFrom: 99,
  },
  {
    id: "clips-sunflower-duo",
    title: "Sunflower clip duo",
    category: "Clips & brooches",
    image: "/products/clips-sunflower-duo.jpg",
    blurb: "Two sunflowers with green leaf backs.",
    priceFrom: 99,
  },
  {
    id: "clips-pastel-pearl",
    title: "Pastel pearl clips",
    category: "Clips & brooches",
    image: "/products/clips-pastel-pearl.jpg",
    blurb: "Four soft shades with pearl centres — set of four.",
    priceFrom: 149,
  },
  {
    id: "hairtie-lilac",
    title: "Lilac flower hair tie",
    category: "Clips & brooches",
    image: "/products/hairtie-lilac.jpg",
    blurb: "A chunky bloom on a soft elastic — everyday wear.",
    priceFrom: 99,
  },
  {
    id: "hair-crown-blue",
    title: "Blue flower crown",
    category: "Clips & brooches",
    image: "/products/hair-crown-blue.jpg",
    blurb: "A halo of powder-blue blooms on a green vine band.",
    priceFrom: 299,
  },
  {
    id: "hair-gajra-lilac",
    title: "Lilac gajra",
    category: "Clips & brooches",
    image: "/products/hair-gajra-lilac.jpg",
    blurb: "A ring of small purple flowers on a vine — for a bun or braid.",
    priceFrom: 199,
  },
  {
    id: "brooch-red-hibiscus",
    title: "Red hibiscus brooch",
    category: "Clips & brooches",
    image: "/products/brooch-red-hibiscus.jpg",
    blurb: "Hibiscus with a long stem and leaves — pin it to a saree pallu.",
    priceFrom: 149,
  },
  {
    id: "clips-return-gift-pack",
    title: "Return gift pack",
    category: "Clips & brooches",
    image: "/products/clips-return-gift-pack.jpg",
    blurb: "Carded flower clips, ready to hand out — mix the colours as you like.",
    priceFrom: 449,
  },
  {
    id: "toran-shubh-labh",
    title: "Shubh Labh door set",
    category: "Torans & garlands",
    image: "/products/toran-shubh-labh.jpg",
    blurb: "Daisy faces with pearl strands and marigold tails for Diwali doorways.",
    priceFrom: 349,
  },
  {
    id: "toran-pearl-latkan-pair",
    title: "Pearl latkan pair",
    category: "Torans & garlands",
    image: "/products/toran-pearl-latkan-pair.jpg",
    blurb: "Purple, red and white blooms on pearl drops — hang either side of a door.",
    priceFrom: 249,
  },
  {
    id: "toran-marigold-latkan",
    title: "Marigold latkan",
    category: "Torans & garlands",
    image: "/products/toran-marigold-latkan.jpg",
    blurb: "Yellow bunches on a pearl string — light, and it never wilts.",
    priceFrom: 199,
  },
  {
    id: "toran-nazar-hanging",
    title: "Nazar wall hanging",
    category: "Torans & garlands",
    image: "/products/toran-nazar-hanging.jpg",
    blurb: "Evil-eye bloom with pearl drops on a printed board — a housewarming favourite.",
    priceFrom: 299,
  },
  {
    id: "garland-marigold-mala",
    title: "Marigold mala",
    category: "Torans & garlands",
    image: "/products/garland-marigold-mala.jpg",
    blurb: "Orange, white and green — a forever garland for photos and pooja.",
    priceFrom: 199,
  },
  {
    id: "garland-mala-pair",
    title: "Wedding mala pair",
    category: "Torans & garlands",
    image: "/products/garland-mala-pair.jpg",
    blurb: "Two matching orange-and-white garlands for the couple.",
    priceFrom: 449,
  },
  {
    id: "decor-ganpati-hibiscus",
    title: "Ganpati flower decor",
    category: "Torans & garlands",
    image: "/products/decor-ganpati-hibiscus.jpg",
    blurb: "Red hibiscus made to order for the festival mandap.",
    priceFrom: 499,
  },
];

/** Shown as the catalogue preview on the home page. */
export const featuredProductIds = [
  "bouquet-pink-gerbera",
  "toran-shubh-labh",
  "keychain-sunflower-yellow",
  "clips-pastel-pearl",
  "bouquet-blue-gerbera",
  "garland-mala-pair",
  "magnet-sunflower-bunch",
  "hair-crown-blue",
];

export const categories: ProductCategory[] = [
  "Bouquets",
  "Keychains",
  "Magnets & pots",
  "Clips & brooches",
  "Torans & garlands",
];

export const occasionPacks = [
  {
    id: "birthday",
    title: "Birthday bloom",
    blurb: "One gift bouquet + optional gift note. Bright, ready to surprise.",
    includes: ["1 forever bouquet", "Gift wrap", "Optional handwritten note"],
    from: 349,
    image: "/products/16-5553eaee-0675-49f1-a938-35f2897f1d5e.png",
    message:
      "Hi Magic Hands Creation! I'd like the Birthday bloom pack (bouquet + gift wrap). Preferred colors:",
  },
  {
    id: "return-gifts",
    title: "Return gifts (10 pcs)",
    blurb: "Party packs of keychains or clips — same style, mixed colors.",
    includes: ["10 keychains or clips", "Matching color theme", "Bulk discount"],
    from: 449,
    image: "/products/15-b378e372-4770-40e4-8444-c5d16d6b7704.png",
    message:
      "Hi Magic Hands Creation! I'd like a Return gifts pack of 10 pieces. Preference: keychains / clips. Theme colors:",
  },
  {
    id: "teachers-day",
    title: "Teacher’s day mini",
    blurb: "A tiny pot or sunflower pin — thoughtful and lasts forever.",
    includes: ["1 mini pot or brooch", "Cute wrap", "Optional thank-you note"],
    from: 129,
    image: "/products/24-5ee1725c-b4fe-4674-b45f-ebb46dac0267.png",
    message:
      "Hi Magic Hands Creation! I'd like the Teacher's day mini pack. Prefer pot / brooch. Note text:",
  },
];

/** Edit this for each exhibition / stall */
export const stallSchedule = {
  headline: "Meet us at The MAGNET",
  event: "Ritu Agrawal’s The MAGNET Fashion & Lifestyle Exhibition",
  location: "Kesar Bagh, N-3 CIDCO",
  area: "Chhatrapati Sambhajinagar",
  when: "19th & 20th August 2026",
  stallNo: "Stall No. 07",
  nextDate: "Two days only — fashion & lifestyle exhibition",
  note: "Handcrafted gifts, rakhis, bouquets, keychains & hampers. Message us to reserve a piece before you visit.",
  mapHint: "Ask for directions or a live pin on WhatsApp.",
  makers: "Handcrafted with love by Vrushali Deokar & Ashwini Deokar",
  flyer: "/exhibition-flyer.png",
  flyerCropped: "/exhibition-flyer-cropped.png",
  whatsappAlt: "919067974603",
};

export const flowerColors = [
  { id: "sunflower", label: "Sunflower yellow", swatch: "#f0c23a" },
  { id: "coral", label: "Coral orange", swatch: "#e8733a" },
  { id: "blush", label: "Blush pink", swatch: "#e8a0b0" },
  { id: "crimson", label: "Crimson red", swatch: "#c2303a" },
  { id: "lavender", label: "Lavender", swatch: "#9b7bb8" },
  { id: "white", label: "Soft white", swatch: "#f5f0e8" },
  { id: "sky", label: "Sky blue", swatch: "#6ba3c9" },
  { id: "mint", label: "Mint green", swatch: "#7cbc8a" },
];

export const wrapColors = [
  { id: "black-mesh", label: "Black mesh", swatch: "#1a1a1a" },
  { id: "cream", label: "Cream paper", swatch: "#f3ead8" },
  { id: "white-tulle", label: "White tulle", swatch: "#ffffff" },
  { id: "lilac", label: "Lilac mesh", swatch: "#c9b0d8" },
  { id: "gold-trim", label: "Gold-trim wrap", swatch: "#d4a84b" },
];

export const makingSteps = [
  {
    title: "Twist the petals",
    text: "Each bloom starts as soft chenille stems, looped by hand into petals.",
    image: "/products/25-64c4072e-1530-4653-b6c2-bebeb20aa6db.png",
  },
  {
    title: "Shape the gift",
    text: "Stems, leaves, and wraps come together into bouquets, pots, and charms.",
    image: "/products/18-f7d9f4a8-c8fa-4835-843b-3841711ad9f5.png",
  },
  {
    title: "Ready for you",
    text: "Finished pieces hit the stall rack — or your WhatsApp order list.",
    image: "/products/15-b378e372-4770-40e4-8444-c5d16d6b7704.png",
  },
];
